POST http://localhost:8000/api/create
Content-Type: application/json

{
    "book_id":202,
    "book_name":"machine Learning"
}


###

PUT http://localhost:8000/api/update/202
Content-Type: application/json

{
    "book_name":"hello world"
}

### 

DELETE http://localhost:8000/api/delete/202

###

GET http://localhost:8000/api/showdata

###

POST http://localhost:8000/api/borow
Content-Type: application/json

{
    "name":"i am",
    "email":"thss@gmail.com",
    "book_id":202
}

###

GET http://localhost:8000/api/showUser