BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Books CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


-- create Books table
CREATE TABLE Books (
    book_id        VARCHAR2(20)   PRIMARY KEY,
    book_name      VARCHAR2(100)  NOT NULL,
    is_borrowed    NUMBER(1)      DEFAULT 0 NOT NULL,  -- 0 = available, 1 = borrowed
    borrowed_user_id NUMBER       DEFAULT NULL,

    CONSTRAINT chk_is_borrowed CHECK (is_borrowed IN (0, 1))
);

-- Create Users table`
CREATE TABLE Users (
    id      NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100)  NOT NULL,
    email   VARCHAR2(100)  NOT NULL,
    book_id VARCHAR2(20)   NOT NULL,

    CONSTRAINT fk_user_book FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

-- create history table
CREATE TABLE History (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     VARCHAR2(20) NOT NULL,
    user_id     NUMBER NOT NULL, -- Link to the User ID instead
    borrow_date DATE DEFAULT SYSDATE,

    CONSTRAINT fk_history_book FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

-- Alter table and add a user_name column and drop the fk_history_user foreign key

ALTER TABLE History ADD user_name VARCHAR2(100);
ALTER TABLE History DROP CONSTRAINT fk_history_user;

-- Insert History data
INSERT INTO History (book_id, user_id, user_name)
VALUES ('B001', 7, 'datta');
DELETE FROM USERS
WHERE id = 7;
SELECT * FROM History;
UPDATE Books SET is_borrowed = 0 WHERE book_id = 'B001';
COMMIT;

-- Insert book data
INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B001', 'Introduction to Algorithms', 0, NULL);

INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B002', 'Database System Concepts', 0, NULL);

INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B003', 'Clean Code', 0, NULL);

-- Insert brrower data
INSERT INTO Users (name, email, book_id)
VALUES ('datta', 'jojewardattatray@gmail.com','B001');
UPDATE Books SET is_borrowed = 1 WHERE book_id = 'B001';
COMMIT;

TRUNCATE TABLE Users;
TRUNCATE TABLE Books;
TRUNCATE TABLE History;
DROP TABLE Users;
DROP TABLE Books;

SELECT * FROM Users;
SELECT * FROM Books;