CREATE TABLE books (
    book_id VARCHAR2 PRIMARY KEY,
    book_name VARCHAR2(100) NOT NULL
);


INSERT INTO books(book_id, book_name)
VALUES (101, 'python');

SELECT * from books;


CREATE TABLE user_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    PRIMARY KEY (id)
)


UPDATE books SET name = book_name WHERE book_id = book_id;


ALTER TABLE books MODIFY book_id VARCHAR2(100);


TRUNCATE TABLE books;

