-- ============================================================
--  Library Management System — Oracle DB Schema
-- ============================================================

-- Drop tables if they already exist (safe re-run)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Books CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ------------------------------------------------------------
--  Table: Books
-- ------------------------------------------------------------
CREATE TABLE Books (
    book_id        VARCHAR2(20)   PRIMARY KEY,
    book_name      VARCHAR2(100)  NOT NULL,
    is_borrowed    NUMBER(1)      DEFAULT 0 NOT NULL,  -- 0 = available, 1 = borrowed
    borrowed_user_id NUMBER       DEFAULT NULL,

    CONSTRAINT chk_is_borrowed CHECK (is_borrowed IN (0, 1))
);

-- ------------------------------------------------------------
--  Table: Users
-- ------------------------------------------------------------
CREATE TABLE Users (
    id      NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100)  NOT NULL,
    email   VARCHAR2(100)  NOT NULL,
    book_id VARCHAR2(20)   NOT NULL,

    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

-- ------------------------------------------------------------
--  Sample Data
-- ------------------------------------------------------------
INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B001', 'Introduction to Algorithms', 0, NULL);

INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B002', 'Database System Concepts', 0, NULL);

INSERT INTO Books (book_id, book_name, is_borrowed, borrowed_user_id)
VALUES ('B003', 'Clean Code', 0, NULL);

COMMIT;


SELECT * FROM Users;