CREATE TABLE books (
    book_id VARCHAR2 PRIMARY KEY,
    book_name VARCHAR2(100) NOT NULL,
    is_Borowed BOOLEAN,
    borowed_user_id 
);


INSERT INTO books(book_id, book_name)
VALUES (101, 'python');

SELECT * from books;


CREATE TABLE user_test (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    PRIMARY KEY (id)
)


CREATE TABLE Users (
    id NUMBER GENERATED by DEFAULT as IDENTITY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    PRIMARY KEY (id),
    Book_id VARCHAR2(100),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);


ALTER TABLE Users
ADD CONSTRAINT book_id
FOREIGN KEY (book_id)
REFERENCES books(book_id)



INSERT INTO Users(name, email,book_id)
VALUES ('datta2', 'datta2@gmail.com',202);


SELECT * from Users;


UPDATE books SET name = book_name WHERE book_id = book_id;


ALTER TABLE books MODIFY book_id VARCHAR2(100);


TRUNCATE TABLE Users;