-- Main Table
CREATE TABLE Library (
    book_id NUMBER PRIMARY KEY,
    book_name VARCHAR2(100),
    quantity NUMBER
);

-- Audit Table (to store old values)
CREATE TABLE Library_Audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    book_id NUMBER,
    book_name VARCHAR2(100),
    quantity NUMBER,
    action_type VARCHAR2(20), -- UPDATE / DELETE
    action_date DATE
);

-- BEFORE UPDATE TRIGGER (ROW LEVEL)
CREATE OR REPLACE TRIGGER trg_before_update
BEFORE UPDATE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit
    VALUES (
        DEFAULT,
        :OLD.book_id,
        :OLD.book_name,
        :OLD.quantity,
        'BEFORE UPDATE',
        SYSDATE
    );
END;
/

-- AFTER UPDATE TRIGGER (ROW LEVEL)
CREATE OR REPLACE TRIGGER trg_after_update
AFTER UPDATE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit
    VALUES (
        DEFAULT,
        :OLD.book_id,
        :OLD.book_name,
        :OLD.quantity,
        'AFTER UPDATE',
        SYSDATE
    );
END;
/


-- BEFORE DELETE TRIGGER (ROW LEVEL)
CREATE OR REPLACE TRIGGER trg_before_delete
BEFORE DELETE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit
    VALUES (
        DEFAULT,
        :OLD.book_id,
        :OLD.book_name,
        :OLD.quantity,
        'BEFORE DELETE',
        SYSDATE
    );
END;
/


-- AFTER DELETE TRIGGER (ROW LEVEL)
CREATE OR REPLACE TRIGGER trg_after_delete
AFTER DELETE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit
    VALUES (
        DEFAULT,
        :OLD.book_id,
        :OLD.book_name,
        :OLD.quantity,
        'AFTER DELETE',
        SYSDATE
    );
END;
/


-- BEFORE UPDATE (STATEMENT LEVEL)
CREATE OR REPLACE TRIGGER trg_stmt_before_update
BEFORE UPDATE ON Library
BEGIN
    DBMS_OUTPUT.PUT_LINE('Before Update Statement Executed');
END;
/

-- AFTER DELETE (STATEMENT LEVEL)
CREATE OR REPLACE TRIGGER trg_stmt_after_delete
AFTER DELETE ON Library
BEGIN
    DBMS_OUTPUT.PUT_LINE('After Delete Statement Executed');
END;
/

-- Insert sample data
INSERT INTO Library VALUES (1, 'DBMS Book', 10);

-- Update
UPDATE Library SET quantity = 5 WHERE book_id = 1;

-- Delete
DELETE FROM Library WHERE book_id = 1;

-- Check audit table
SELECT * FROM Library_Audit;